# Generated by Django 4.1.2 on 2022-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='market',
            name='season',
            field=models.CharField(default='Memorial Day- Labor Day', max_length=100),
        ),
        migrations.AddField(
            model_name='market',
            name='state',
            field=models.CharField(default='DMV', max_length=5),
        ),
        migrations.AddField(
            model_name='market',
            name='times',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='day',
            field=models.CharField(default='Saturday', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/photos/veggie-market-picture-id840320076?s=612x612', max_length=300),
        ),
    ]
