# Generated by Django 4.1.2 on 2022-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_address_market_location_market_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('website', models.CharField(max_length=150)),
                ('markets', models.ManyToManyField(to='main_app.market')),
            ],
        ),
    ]
