# Generated by Django 4.1.2 on 2022-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/', max_length=300),
        ),
    ]
