# Generated by Django 4.1.2 on 2022-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_vendor_market_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='county',
            field=models.CharField(default='Frederick', max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='times',
            field=models.CharField(default='10am-1pm', max_length=100),
        ),
    ]
