# Generated by Django 4.1.2 on 2022-10-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_product_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
